using System;
using UnityEngine;
using UnityEditor;
using GT_CustomMapSupportRuntime;

namespace Ghosty.Things
{
    public enum SoundOverrides
    {
        Default = 0,
        None = 1,
        PillowHandTap = 3,
        GrassRockHandTap = 7,
        BarkHandTap = 8,
        WoodHandTap = 9,
        DirtHandTap = 14,
        MetalHandTap = 18,
        CrystalHandTap = 20,
        LeafCrunch = 31,
        SnowStep = 32,
        CrystalHandTap_Root_2octdown = 40,
        CrystalHandTap_Second_2octdown = 41,
        CrystalHandTap_Third_2octdown = 42,
        CrystalHandTap_Fifth_2octdown = 43,
        CrystalHandTap_Sixth_2octdown = 44,
        CrystalHandTap_Root_1octdown = 45,
        CrystalHandTap_Second_1octdown = 46,
        CrystalHandTap_Third_1octdown = 47,
        CrystalHandTap_Fifth_1octdown = 48,
        CrystalHandTap_Sixth_1octdown = 49,
        CrystalHandTap_Root = 50,
        CrystalHandTap_Root_Second = 51,
        CrystalHandTap_Third = 52,
        CrystalHandTap_Fifth = 53,
        CrystalHandTap_Sixth = 54,
        UmbrellaOpen = 64,
        UmbrellaClose = 65,
        KeyboardClick = 66,
        ButtonPress = 67,
        P2_RackTom = 68,
        P1_Snare = 69,
        P2_Floor_Tom_2 = 70,
        P2_Kick = 71,
        P1_Open_Hat = 72,
        BongoLowest = 73,
        BongoHigh = 74,
        Squeak_Squeeze = 75,
        Squeak_Release = 76,
        BoneRattle = 77,
        Tombstone_Surface_04 = 78,
        CauldronInner = 79,
        Cauldron_Surface_04 = 80,
        PumpkinHit = 81,
        Web_Surface_02 = 82,
        ShortTurkeyGobbleBQuiet = 83,
        FoodPop = 84,
        Bite1 = 85,
        Bite2 = 86,
        Bite3 = 87,
        HayImpactA = 88,
        RopeCreak = 89,
        PlantHit = 90,
        ToyFrogSound = 91,
        VineHit1 = 92,
        Cloud2 = 93,
        WoodFloor2 = 94,
        Tire = 95,
        FruitSquish_1 = 96,
        WashingMachineHit = 98,
        LeafHit1 = 99,
        SkyJungleWood2 = 100,
        SkyJungleWood = 101,
        HutHit = 105,
        FireflyJarHit = 106,
        Beanbag1 = 107,
        Beanbag2 = 108,
        SoftHit1 = 110,
        StoreWoodHit = 112,
        ShelfHit = 114,
        RoofHit = 115,
        CraneHit = 116,
        RugHit1 = 118,
        SnowglobeHit = 120,
        OrnamentHit = 121,
        GiftHit = 134,
        ToyGorillaElf_Squeeze = 140,
        ToyGorillaElf_Release = 141,
        MetalHit1 = 146,
        MetalHit2 = 149,
        PenguinSqueeze = 154,
        PenguinRelease = 155,
        WolfSqueeze = 156,
        WolfRelease = 157,
        BoxHit = 160,
        DungeonPillowHit = 164,
        BasementWoodWall = 173,
        BookHit = 178,
        MonkeyeSqueeze = 187,
        DragonSqueeze = 188,
        ConcreteHit = 189,
        BeeSqueeze = 191,
        SpongeSquish = 193,
        SpongeRelease = 194,
        CoyoteHowl_Quiet2 = 195,
        DivingBoardBounce = 196,
        SandTap = 197,
        PalmTreeBark = 198,
        SharkSqueeze = 200,
        SharkRelease = 201,
        TentBounce = 202,
        FireworkMortar = 203,
        WaterBalloonGrab = 204,
        SlipAndSlideStep = 205,
        DolphinSqueeze3 = 206,
        DolphinRelease3 = 207,
        BugSprayShort = 208,
        Trampoline1 = 210,
        ButtonSplitDown = 211,
        ButtonSplitUp = 212,
        HugeCrystalHit = 213,
        CrystalHandTap_Seventh = 214,
        CrystalHandTap_Seventh_1octup = 215,
        CrystalHandTap_Seventh_1octdown = 216,
        CrystalHandTap_Seventh_2octdown = 217,
        CrystalHandTap_Fourth = 218,
        CrystalHandTap_Fourth_1octdown = 219,
        CrystalHandTap_Fourth_1octup = 220,
        CrystalHandTap_Fourth_2octdown = 221,
        EelSqueeze = 222,
        EelRelease = 223,
        CrystalHandTap_Root_1octup = 224,
        CrystalHandTap_Second_1octup = 225,
        CrystalHandTap_Third_1octup = 226,
        CrystalHandTap_Fifth_1octup = 227,
        CrystalHandTap_Sixth_1octup = 228,
        BottleSqueeze = 229,
        BrokenLavaRocks = 231,
        PhoenixCaw = 232,
        FanOpen = 233,
        FanClose = 234,
        CatSqueeze = 235,
        CatRelease = 236,
        SquirrelToy = 237,
        TurkeyBaster1 = 238,
        TurkeyBaster2 = 239,
        Presents_Gifts = 240,
        TinSoldier1 = 242,
        TinSoldier2 = 243,
        TuningFork1 = 244,
        TuningFork2 = 245,
        TuningForkFail = 246,
        TuningForkDeep = 247,
        TuningForkNeutral = 248,
        ConfettiCandy = 249,
        HeartSqueeze = 250,
        HeartBeat1 = 251,
        GiantMeatballs = 252,
        BellowsOut = 253,
        BellowsIn = 254,
        RaceBell = 255,
        BounceHouse1 = 256,
        BounceHouse2 = 257,
        PurpleStep = 258,
        GateFenceClose = 259,
        HalloweenCandyBucket = 286,
        WorkingLavaRocks = 287,
        Apple = 288,
        EasterEggs = 311,
        Book = 312,
        GoldCoin = 313,
        HotDog = 314,
        IceCream = 315,
        Fireworks = 316,
        Paper = 317,
        IcecreamScoop = 318,
        Chips = 322,
        RedBall = 323,
        TacoBall = 324,
        MashedPotatoes = 325,
        BreadBall = 326,
        PurpleBall = 327,
        OrangeBall = 328,
        Stuffing = 329,
        Turkey = 330,
        Corn = 331,
        FireStick = 332,
        FoodBall = 333,
        PineappleFootball = 334,
        Popcorn = 335,
        BigSnowball = 339,
        FlamingNuts = 340
    }

    [CustomEditor(typeof(SurfaceOverrideSettings))]
    public class SurfaceOverrideSettingsEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            SurfaceOverrideSettings settings = (SurfaceOverrideSettings)target;

            string[] options = Enum.GetNames(typeof(SoundOverrides));
            int[] intValues = (int[])Enum.GetValues(typeof(SoundOverrides));

            int currentIndex = Array.IndexOf(intValues, (int)settings.soundOverride);
            if (currentIndex < 0) currentIndex = 0;

            int selectedIndex = EditorGUILayout.Popup("Sound Override", currentIndex, options);
            settings.soundOverride = (SurfaceSoundOverride)intValues[selectedIndex];

            DrawPropertiesExcluding(serializedObject, "soundOverride", "m_Script");

            if (GUI.changed)
                EditorUtility.SetDirty(settings);
        }
    }
}